### PR TITLE
Feature/mock tests

### PR DESCRIPTION
**Pull request by Andreichenko**
tests

### CODE REVIEW

**Comment by volnov** [comment]
👍

**Comment by Andreichenko** [comment]
12:30:46  > Task :test
12:30:46  
12:30:46  bot.commands.alias.AliasCreateCommandTest > testAliasCantBeCreatedWhenCommandCantBeFound PASSED
12:30:47  
12:30:47  bot.commands.alias.AliasCreateCommandTest > testAliasCreatesSomeSuccessfullyForSingleWordArguments PASSED
12:30:48  
12:30:48  bot.commands.alias.AliasCreateCommandTest > testFailsSuccessfullyIfAliasCantBeDeleted PASSED
12:30:48  
12:30:48  bot.commands.alias.AliasCreateCommandTest > testAliasIsDeletedIfItAlreadyExists PASSED
12:30:48  
12:30:48  bot.commands.alias.AliasCreateCommandTest > testAliasCreateSomeSuccessfullyValueForMultiWordArguments PASSED
12:30:49  
12:30:49  bot.commands.alias.AliasCreateCommandTest > testSomeAliasExecutesSuccessfully PASSED
12:30:49  
12:30:49  bot.commands.alias.AliasCreateCommandTest > testAliasCantBeCreatedWhenNotAllParametersAreProvided PASSED
12:30:49  
12:30:49  bot.commands.alias.AliasCreateCommandTest > testAliasCantBeCreatedWithSameNameAsExistingCommand PASSED
12:30:49  
12:30:49  bot.commands.alias.AliasDeleteCommandTests > testSuccessfullyDeleteAlias PASSED
12:30:49  
12:30:49  bot.commands.alias.AliasDeleteCommandTests > testFailsSuccessfullyWhenNoArgIsSent PASSED
12:30:49  
12:30:49  bot.commands.alias.AliasDeleteCommandTests > testFailsSuccessfullyWhenAliasDoesNotExist PASSED
12:30:49  
12:30:49  bot.commands.alias.AliasDeleteCommandTests > testFailsSuccessfullyWhenAliasCantBeDeleted PASSED
12:30:49  
12:30:49  bot.commands.alias.AliasListCommandTest > testListReturnsWhenThereAreNoAliases PASSED
12:30:49  
12:30:49  bot.commands.alias.AliasListCommandTest > testListReturnsMultipleAliases PASSED
12:30:49  
12:30:49  Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
12:30:49  Use '--warning-mode all' to show the individual deprecation warnings.
12:30:49  See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
12:30:49  
12:30:49  BUILD SUCCESSFUL in 54s
12:30:49  6 actionable tasks: 6 executed

**Comment by Andreichenko** [comment]
Screen Shot 2020-12-17 at 1 03 55 PM

**Comment by Andreichenko** [comment]
Screen Shot 2020-12-17 at 3 46 56 PM

**Pull request merged**
